### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by matwey** [gogo/protobuf#131]
Hello,

I am building gogo protobuf with go 1.5.2 and sometimes see the following:

```
[  287s] /usr/lib64/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/gogo/protobuf/test/theproto3/combos/unmarshaler.a -trimpath $WORK -p github.com/gogo/protobuf/test/theproto3/combos/unmarshaler -complete -buildid 5e5a1fc67a941a3dc411e0244e445fddea156615 -D _/home/abuild/rpmbuild/BUILD/go/src/github.com/gogo/protobuf/test/theproto3/combos/unmarshaler -I $WORK -I /home/abuild/rpmbuild/BUILD/go/pkg/linux_amd64 -pack ./theproto3.pb.go
[  346s] # github.com/gogo/protobuf/test/theproto3/combos/neither
[  346s] SIGILL: illegal instruction
[  346s] PC=0x7ffedab5fc79 m=1
[  346s] 
[  346s] goroutine 0 [idle]:
[  346s] 
[  346s] goroutine 1 [runnable]:
[  346s] cmd/compile/internal/amd64.proginfo(0xc826de3680)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/amd64/prog.go:263
[  346s] cmd/compile/internal/gc.Flowstart(0xc826e1a6c0, 0x0, 0x0)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/popt.go:252 +0x91
[  346s] cmd/compile/internal/gc.mergetemp(0xc826e1a6c0)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/popt.go:574 +0x5e
[  346s] cmd/compile/internal/gc.regopt(0xc826e1a6c0)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/reg.go:1037 +0x4f
[  346s] cmd/compile/internal/gc.compile(0xc8227ff950)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/pgen.go:508 +0xe82
[  346s] cmd/compile/internal/gc.funccompile(0xc8227ff950)
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/dcl.go:1484 +0x1c9
[  346s] cmd/compile/internal/gc.Main()
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/gc/lex.go:473 +0x1f08
[  346s] cmd/compile/internal/amd64.Main()
[  346s] 	/usr/lib64/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
[  346s] main.main()
[  346s] 	/usr/lib64/go/src/cmd/compile/main.go:26 +0x189
[  346s] 
[  346s] rax    0x56797abf
[  346s] rbx    0x0
[  346s] rcx    0xc820000480
[  346s] rdx    0x2
[  346s] rdi    0x0
[  346s] rsi    0xc82003fed8
[  346s] rbp    0xc82003fec8
[  346s] rsp    0xc82003fe98
[  346s] r8     0xc82003fef0
[  346s] r9     0x0
[  346s] r10    0x0
[  346s] r11    0x246
[  346s] r12    0x1f638
[  346s] r13    0xc82003fea4
[  346s] r14    0x25e897000000000
[  346s] r15    0x8
[  346s] rip    0x7ffedab5fc79
[  346s] rflags 0x10246
[  346s] cs     0x33
[  346s] fs     0x0
[  346s] gs     0x0
[  346s] github.com/gogo/protobuf/test/theproto3/combos/unsafeboth
```

**Comment by awalterschulze** [comment]
Isn't this more of a go issue than a gogoprotobuf issue?

**Comment by matwey** [comment]
@awalterschulze frankly speaking, I don't speak go, but this appears only with gogoprotobuf. So It could be go issue induced by protobuf.

**Comment by awalterschulze** [comment]
I am on holiday.  I will be back next week.  Maybe you could report this as a go issue in the mean time.

**Comment by awalterschulze** [comment]
I have updated the travis tests to test go1.5.2, but I don't seem to encounter the same issue.

Have you made any progress with reporting this go issue?
The go compiler is not supposed to throw a stack trace.
It should give an appropriate compiler error.

**Comment by matwey** [comment]
Yes, I reported to upstream because it happens not only with protobuf.
https://github.com/golang/go/issues/13735

**Comment by awalterschulze** [comment]
Ok great.  Thank you for linking the issue.

**Comment by awalterschulze** [comment]
I am going to close this, since its really a go issue.
Please object if you feel differently.
