### ISSUE TITLE
Tags test fails with go 1.8rc3

### ISSUE THREAD

**Issue by Civil** [gogo/protobuf#259]
As go 1.8 should be released this week, I think it might worth to find out what's the issue with this test.
```
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/gogo/protobuf/test/tags $ /usr/local/Cellar/go/1.7.5/bin/go version
go version go1.7.5 darwin/amd64
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/gogo/protobuf/test/tags $ /usr/local/Cellar/go/1.7.5/bin/go test
PASS
ok     	github.com/gogo/protobuf/test/tags     	0.014s
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/gogo/protobuf/test/tags $ go version
go version go1.8rc3 darwin/amd64
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/gogo/protobuf/test/tags $ go test
--- FAIL: TestXml (0.00s)
panic: xml: bad type for comment field of tags.Outside [recovered]
       	panic: xml: bad type for comment field of tags.Outside

goroutine 6 [running]:
testing.tRunner.func1(0xc420072b60)
       	/Users/vsmirnov/gentoo/usr/lib/go/src/testing/testing.go:622 +0x29d
panic(0x119d920, 0xc42000f250)
       	/Users/vsmirnov/gentoo/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/gogo/protobuf/test/tags.TestXml(0xc420072b60)
       	/Users/vsmirnov/go/gopath_third_party/src/github.com/gogo/protobuf/test/tags/tags_test.go:114 +0x5a0
testing.tRunner(0xc420072b60, 0x11e0958)
       	/Users/vsmirnov/gentoo/usr/lib/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
       	/Users/vsmirnov/gentoo/usr/lib/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL   	github.com/gogo/protobuf/test/tags     	0.018s
```

**Comment by awalterschulze** [comment]
Thank you

So this works in go1.7.5, but not in go1.8rc3

```go
package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
)

type Outside struct {
	*Inside          `json:""`
	Field2           *string `json:"MyField2" xml:",comment"`
	XXX_unrecognized []byte  `json:"-"`
}

type Inside struct {
	Field1           *string `json:"MyField1" xml:",chardata"`
	XXX_unrecognized []byte  `json:"-"`
}

func main() {
	s := "<Outside>Field1Value<!--Field2Value--><XXX_unrecognized></XXX_unrecognized></Outside>"
	field1 := "Field1Value"
	field2 := "Field2Value"
	msg1 := &Outside{}
	err := xml.Unmarshal([]byte(s), msg1)
	if err != nil {
		panic(err)
	}
	msg2 := &Outside{
		Inside: &Inside{
			Field1: &field1,
		},
		Field2: &field2,
	}
	if *msg1.Field1 != *msg2.Field1 {
		panic(fmt.Errorf("field1 expected %s got %s", *msg2.Field1, *msg1.Field1))
	}
	if err != nil {
		panic(err)
	}
	data, err := xml.Marshal(msg2)
	if err != nil {
		panic(err)
	}
	if !bytes.Equal(data, []byte(s)) {
		panic(fmt.Errorf("expected %s got %s", s, string(data)))
	}
}
```

**Comment by awalterschulze** [comment]
Or even smaller

```go

package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
)

type Outside struct {
	Field2 *string `json:"MyField2" xml:",comment"`
}

func main() {
	s := "<Outside><!--Field2Value--></Outside>"
	field2 := "Field2Value"
	msg1 := &Outside{}
	err := xml.Unmarshal([]byte(s), msg1)
	if err != nil {
		panic(err)
	}
	msg2 := &Outside{
		Field2: &field2,
	}
	data, err := xml.Marshal(msg2)
	if err != nil {
		panic(err)
	}
	if !bytes.Equal(data, []byte(s)) {
		panic(fmt.Errorf("expected %s got %s", s, string(data)))
	}
}

```

**Comment by awalterschulze** [comment]
https://github.com/golang/go/issues/19063

**Comment by awalterschulze** [comment]
golang has fixed the issue, so it should be fixed now.
