### ISSUE TITLE
gogoprotobuf proto.Unmarshal crashes with segfault

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#29]
_From [J.E.A...@gmail.com](https://code.google.com/u/112062146291360219455/) on November 08, 2014 19:44:30_

What steps will reproduce the problem? 1. send a big protocol buffer
2. on receipt, try to decode it
3. watch it crash the program trying to decode a varint

Here is the stack trace:

unexpected fault address 0x7f8581ad3175
fatal error: fault
[signal 0xb code=0x1 addr=0x7f8581ad3175 pc=0x632e7f]

goroutine 38 [running]:
runtime.throw(0x145af62)
    /home/jaten/pkg/go1.3.1/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x7f85dc27d178 sp=0x7f85dc27d160
runtime.sigpanic()
    /home/jaten/pkg/go1.3.1/go/src/pkg/runtime/os_linux.c:240 +0x13f fp=0x7f85dc27d190 sp=0x7f85dc27d178
code.google.com/p/gogoprotobuf/proto.(*Buffer).DecodeVarint(0xc22f541ba0, 0x0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:92 +0x8f fp=0x7f85dc27d1b0 sp=0x7f85dc27d190
code.google.com/p/gogoprotobuf/proto.(*Buffer).DecodeRawBytes(0xc22f541ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:179 +0x73 fp=0x7f85dc27d280 sp=0x7f85dc27d1b0
code.google.com/p/gogoprotobuf/proto.(*Buffer).dec_slice_ref_struct(0xc22f541ba0, 0xc2081007e0, 0x0, 0xc3779eeb00, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode_gogo.go:112 +0xe2 fp=0x7f85dc27d328 sp=0x7f85dc27d280
code.google.com/p/gogoprotobuf/proto.(*Buffer).dec_slice_ref_struct_message(0xc22f541ba0, 0xc2081007e0, 0xc3779eeb00, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode_gogo.go:137 +0x52 fp=0x7f85dc27d360 sp=0x7f85dc27d328
code.google.com/p/gogoprotobuf/proto.(*Buffer).unmarshalType(0xc22f541ba0, 0x7f85dfe8c1d8, 0xa3d080, 0xc28d2ba3f0, 0xc3779eeb00, 0xc3779eeb00, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:404 +0xd2f fp=0x7f85dc27d6b8 sp=0x7f85dc27d360
code.google.com/p/gogoprotobuf/proto.(*Buffer).dec_struct_message(0xc22f541ba0, 0xc2081006c0, 0xc22136d9e0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:676 +0x2d7 fp=0x7f85dc27d790 sp=0x7f85dc27d6b8
code.google.com/p/gogoprotobuf/proto.(*Buffer).unmarshalType(0xc22f541ba0, 0x7f85dfe8c1d8, 0xa69780, 0xc28d2ba310, 0xc22136d900, 0xc22136d9e0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:404 +0xd2f fp=0x7f85dc27dae8 sp=0x7f85dc27d790
code.google.com/p/gogoprotobuf/proto.(*Buffer).Unmarshal(0xc22f541ba0, 0x7f85bd02e3c0, 0xc22136d9e0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:334 +0x234 fp=0x7f85dc27dbb0 sp=0x7f85dc27dae8
code.google.com/p/gogoprotobuf/proto.UnmarshalMerge(0x7f8581a60030, 0xe59f46d, 0xe59f46d, 0x7f85bd02e3c0, 0xc22136d9e0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:314 +0x134 fp=0x7f85dc27dc20 sp=0x7f85dc27dbb0
code.google.com/p/gogoprotobuf/proto.Unmarshal(0x7f8581a60030, 0xe59f46d, 0xe59f46d, 0x7f85bd02e3c0, 0xc22136d9e0, 0x0, 0x0)
    /home/jaten/go/src/code.google.com/p/gogoprotobuf/proto/decode.go:300 +0x7a fp=0x7f85dc27dc60 sp=0x7f85dc27dc20
[call from my code into gogoprotobuf Unmarshal() occurs here] What version of the product are you using? On what operating system? ubuntu 12.04 /amd64 / linux 3.2.0-69-generic #103-Ubuntu SMP Tue Sep 2 05:02:14 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux Please provide any additional information below. I'm sending 114MB in a protocol buffer object when this happens, it doesn't seem to happen on very small buffers.

_Original issue: http://code.google.com/p/gogoprotobuf/issues/detail?id=29_

**Comment by awalterschulze** [comment]
I tried https://gist.github.com/awalterschulze/a1d077fa54703017d952 , but I could not reproduce
