### ISSUE TITLE
Fails to build with PPC64el

### ISSUE THREAD

**Issue by TheTincho** [gogo/protobuf#329]
Hi,

We have noticed that gogoprotobuf has started to fail recently on debian build daemons ([log](https://buildd.debian.org/status/fetch.php?pkg=golang-gogoprotobuf&arch=ppc64el&ver=0.3%2Bgit20170120.144.265e960d-2&stamp=1502281675&raw=0)). The same code was not failing in February ([log](https://buildd.debian.org/status/fetch.php?pkg=golang-gogoprotobuf&arch=ppc64el&ver=0.3%2Bgit20170120.144.265e960d-1&stamp=1486523617&raw=0)).

Since then, the only visible change in dependencies is golang, which went from 1.7 to 1.8, so I guess that's where it might be coming from.

I have tried the 0.4 release (the build logs are for commit 265e960d), and I have the same errors.

**Comment by TheTincho** [comment]
Actually, I can confirm the problem is go1.8. I have just tried the same build, forcing go1.7, and I got no failures.

**Comment by awalterschulze** [comment]
Some extracts

```
=== RUN   TestTimerProto
--- FAIL: TestTimerProto (0.00s)
	thetestpb_test.go:4083: seed = 1502281594466825401, err = proto: illegal wireType 6
=== RUN   TestTimerMarshalTo
--- FAIL: TestTimerMarshalTo (0.00s)
	thetestpb_test.go:4122: seed = 1502281594466915440, err = proto: Timer: wiretype end group for non-group
=== RUN   TestMyExtendableProto
--- PASS: TestMyExtendableProto (0.00s)
=== RUN   TestMyExtendableMarshalTo
--- PASS: TestMyExtendableMarshalTo (0.00s)
=== RUN   TestOtherExtenableProto
--- PASS: TestOtherExtenableProto (0.00s)
=== RUN   TestOtherExtenableMarshalTo
--- PASS: TestOtherExtenableMarshalTo (0.00s)
=== RUN   TestNestedDefinitionProto
--- FAIL: TestNestedDefinitionProto (0.00s)
	thetestpb_test.go:4389: seed = 1502281594467379175, err = proto: NestedMessage: wiretype end group for non-group
=== RUN   TestNestedDefinitionMarshalTo
--- FAIL: TestNestedDefinitionMarshalTo (0.00s)
	thetestpb_test.go:4428: seed = 1502281594467485880, err = proto: NestedMessage: wiretype end group for non-group
=== RUN   TestNestedDefinition_NestedMessageProto
--- FAIL: TestNestedDefinition_NestedMessageProto (0.00s)
	thetestpb_test.go:4491: seed = 1502281594467578713, err = proto: NestedMessage: wiretype end group for non-group
=== RUN   TestNestedDefinition_NestedMessageMarshalTo
--- FAIL: TestNestedDefinition_NestedMessageMarshalTo (0.00s)
	thetestpb_test.go:4530: seed = 1502281594467678453, err = proto: illegal wireType 6
=== RUN   TestNestedDefinition_NestedMessage_NestedNestedMsgProto
--- PASS: TestNestedDefinition_NestedMessage_NestedNestedMsgProto (0.00s)
=== RUN   TestNestedDefinition_NestedMessage_NestedNestedMsgMarshalTo
--- PASS: TestNestedDefinition_NestedMessage_NestedNestedMsgMarshalTo (0.00s)
=== RUN   TestNestedScopeProto
--- FAIL: TestNestedScopeProto (0.00s)
	thetestpb_test.go:4695: seed = 1502281594467939400, err = proto: illegal wireType 7
=== RUN   TestNestedScopeMarshalTo
--- FAIL: TestNestedScopeMarshalTo (0.00s)
	thetestpb_test.go:4734: seed = 1502281594468032872, err = proto: illegal wireType 7
```

```
--- FAIL: TestTimerCompare (0.00s)
panic: unexpected EOF [recovered]
	panic: unexpected EOF

goroutine 409 [running]:
testing.tRunner.func1(0xc4202e4410)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x25c
panic(0x3f9920, 0xc420010110)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x284
github.com/gogo/protobuf/test/combos/unsafeboth.TestTimerCompare(0xc4202e4410)
	/<<BUILDDIR>>/golang-gogoprotobuf-0.3+git20170120.144.265e960d/_build/src/github.com/gogo/protobuf/test/combos/unsafeboth/thetestpb_test.go:11716 +0x4b8
testing.tRunner(0xc4202e4410, 0x4677b0)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x9c
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x270
exit status 2
FAIL	github.com/gogo/protobuf/test/combos/unsafeboth	0.080s
```

```
=== RUN   TestTimerProto
--- FAIL: TestTimerProto (0.00s)
	thetestpb_test.go:4083: seed = 1502281600843573611, err = proto: test.Timer: wiretype end group for non-group
=== RUN   TestTimerMarshalTo
--- FAIL: TestTimerMarshalTo (0.00s)
	thetestpb_test.go:4122: seed = 1502281600843698201, err = proto: can't skip unknown wire type 7 for test.Timer
=== RUN   TestMyExtendableProto
--- PASS: TestMyExtendableProto (0.00s)
=== RUN   TestMyExtendableMarshalTo
--- PASS: TestMyExtendableMarshalTo (0.00s)
=== RUN   TestOtherExtenableProto
--- PASS: TestOtherExtenableProto (0.00s)
=== RUN   TestOtherExtenableMarshalTo
--- PASS: TestOtherExtenableMarshalTo (0.00s)
=== RUN   TestNestedDefinitionProto
--- FAIL: TestNestedDefinitionProto (0.00s)
	thetestpb_test.go:4389: seed = 1502281600844271967, err = proto: can't skip unknown wire type 6 for test.NestedDefinition_NestedMessage
=== RUN   TestNestedDefinitionMarshalTo
--- FAIL: TestNestedDefinitionMarshalTo (0.00s)
	thetestpb_test.go:4428: seed = 1502281600844439787, err = proto: can't skip unknown wire type 7 for test.NestedDefinition_NestedMessage
=== RUN   TestNestedDefinition_NestedMessageProto
--- FAIL: TestNestedDefinition_NestedMessageProto (0.00s)
	thetestpb_test.go:4499: seed = 1502281600844568556, &test.NestedDefinition_NestedMessage{XXX_unrecognized:[]byte{0x99, 0x85, 0x64, 0x4e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12, 0x77, 0x52, 0x6, 0x66, 0x4a, 0x65, 0x6d, 0x70, 0x63, 0x85, 0x2, 0x51, 0xac, 0x96, 0xd2, 0x8a, 0x1, 0x50, 0x82, 0x32, 0x63, 0xa, 0xfc, 0xb7, 0x89, 0x84, 0xec, 0x41, 0x5b, 0xf7, 0x12, 0x72, 0xc7, 0x17, 0x57, 0x95, 0x68, 0x23, 0xee, 0x87, 0xe2, 0x1a, 0xae, 0xb2, 0x6d, 0xa7, 0x6b, 0x89, 0x3d, 0x8e, 0x37, 0x84, 0x5a, 0xca, 0x32, 0x69, 0xe4, 0xb2, 0xb9, 0x6d, 0x74, 0xcf, 0x78, 0xbc, 0x31, 0xb4, 0xc2, 0xc6, 0x67, 0xae, 0xe8, 0x16, 0x94, 0x37, 0x8a, 0x55, 0x16, 0xe6, 0x46, 0x37, 0x60, 0x97, 0x59, 0xe6, 0xfd, 0x4f, 0x48, 0x3c, 0x63, 0x4c, 0x39, 0x45, 0xad, 0xf2, 0x9e, 0xdd, 0xb7, 0x26, 0xea, 0x6, 0x13, 0x93, 0xb1, 0x2c, 0xee, 0x6b, 0x34, 0x5, 0x6b, 0xe0, 0x94, 0xf9, 0x38, 0xa5, 0xf3, 0x89, 0x43, 0xe0, 0xac, 0x54, 0x82, 0x1, 0xd, 0x3e, 0xbb, 0xa6, 0x42, 0x3a, 0x6, 0xa8, 0x77, 0x51, 0x4, 0xb6, 0xd6, 0xfe},
		} !VerboseProto &test.NestedDefinition_NestedMessage{NestedField1: func(v uint64) *uint64 { return &v } ( 0x4e648599 ),
		NNM: &test.NestedDefinition_NestedMessage_NestedNestedMsg{NestedNestedField1: func(v string) *string { return &v } ( "fJempc" ),
		XXX_unrecognized:[]byte{0x85, 0x2, 0x51, 0xac, 0x96, 0xd2, 0x8a, 0x1, 0x50, 0x82, 0x32, 0x63, 0xa, 0xfc, 0xb7, 0x89, 0x84, 0xec, 0x41, 0x5b, 0xf7, 0x12, 0x72, 0xc7, 0x17, 0x57, 0x95, 0x68, 0x23, 0xee, 0x87, 0xe2, 0x1a, 0xae, 0xb2, 0x6d, 0xa7, 0x6b, 0x89, 0x3d, 0x8e, 0x37, 0x84, 0x5a, 0xca, 0x32, 0x69, 0xe4, 0xb2, 0xb9, 0x6d, 0x74, 0xcf, 0x78, 0xbc, 0x31, 0xb4, 0xc2, 0xc6, 0x67, 0xae, 0xe8, 0x16, 0x94, 0x37, 0x8a, 0x55, 0x16, 0xe6, 0x46, 0x37, 0x60, 0x97, 0x59, 0xe6, 0xfd, 0x4f, 0x48, 0x3c, 0x63, 0x4c, 0x39, 0x45, 0xad, 0xf2, 0x9e, 0xdd, 0xb7, 0x26, 0xea, 0x6, 0x13, 0x93, 0xb1, 0x2c, 0xee, 0x6b, 0x34, 0x5, 0x6b, 0xe0, 0x94, 0xf9, 0x38, 0xa5, 0xf3, 0x89, 0x43, 0xe0, 0xac, 0x54},
		},
		XXX_unrecognized:[]byte{0x82, 0x1, 0xd, 0x3e, 0xbb, 0xa6, 0x42, 0x3a, 0x6, 0xa8, 0x77, 0x51, 0x4, 0xb6, 0xd6, 0xfe},
		}, since this.NestedField1 == nil && that.NestedField1 != nil
=== RUN   TestNestedDefinition_NestedMessageMarshalTo
--- FAIL: TestNestedDefinition_NestedMessageMarshalTo (0.00s)
	thetestpb_test.go:4530: seed = 1502281600844796950, err = proto: test.NestedDefinition_NestedMessage: illegal tag 0 (wire type 0)
=== RUN   TestNestedDefinition_NestedMessage_NestedNestedMsgProto
--- PASS: TestNestedDefinition_NestedMessage_NestedNestedMsgProto (0.00s)
=== RUN   TestNestedDefinition_NestedMessage_NestedNestedMsgMarshalTo
--- PASS: TestNestedDefinition_NestedMessage_NestedNestedMsgMarshalTo (0.00s)
=== RUN   TestNestedScopeProto
--- PASS: TestNestedScopeProto (0.00s)
=== RUN   TestNestedScopeMarshalTo
--- FAIL: TestNestedScopeMarshalTo (0.00s)
	thetestpb_test.go:4734: seed = 1502281600845236582, err = unexpected EOF
```

```
--- FAIL: TestTimerCompare (0.00s)
panic: proto: can't skip unknown wire type 7 for test.Timer [recovered]
	panic: proto: can't skip unknown wire type 7 for test.Timer

goroutine 186 [running]:
testing.tRunner.func1(0xc420264ea0)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x25c
panic(0x3a9560, 0xc420408650)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x284
github.com/gogo/protobuf/test/combos/unsafemarshaler.TestTimerCompare(0xc420264ea0)
	/<<BUILDDIR>>/golang-gogoprotobuf-0.3+git20170120.144.265e960d/_build/src/github.com/gogo/protobuf/test/combos/unsafemarshaler/thetestpb_test.go:11716 +0x4b8
testing.tRunner(0xc420264ea0, 0x414818)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x9c
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x270
exit status 2
FAIL	github.com/gogo/protobuf/test/combos/unsafemarshaler	0.084s
```

```
--- FAIL: TestAllTypesOneOfProto (0.00s)
	onepb_test.go:107: seed = 1502281632357029605, err = unexpected EOF
```

```
=== RUN   TestSampleOneOfVerboseEqual
--- FAIL: TestSampleOneOfVerboseEqual (0.00s)
panic: proto: wrong wireType = 0 for field Field14 [recovered]
	panic: proto: wrong wireType = 0 for field Field14

goroutine 17 [running]:
testing.tRunner.func1(0xc420110f70)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x25c
panic(0x1ed4e0, 0xc420143b10)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x284
github.com/gogo/protobuf/test/oneof3/combos/unsafeboth.TestSampleOneOfVerboseEqual(0xc420110f70)
	/<<BUILDDIR>>/golang-gogoprotobuf-0.3+git20170120.144.265e960d/_build/src/github.com/gogo/protobuf/test/oneof3/combos/unsafeboth/onepb_test.go:294 +0x2a0
testing.tRunner(0xc420110f70, 0x23e9a8)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x9c
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x270
exit status 2
FAIL	github.com/gogo/protobuf/test/oneof3/combos/unsafeboth	0.011s
```

**Comment by awalterschulze** [comment]
One patten is that these only happen for `<various>/combos/unmarshaler`

**Comment by awalterschulze** [comment]
FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafeboth
FAIL	github.com/gogo/protobuf/test/oneof3/combos/unsafeboth
FAIL	github.com/gogo/protobuf/test/combos/unsafeboth
FAIL	github.com/gogo/protobuf/test/combos/unsafemarshaler

**Comment by awalterschulze** [comment]
So I guess that something in unsafe changed in go1.9

**Comment by awalterschulze** [comment]
I see nothing in the release notes :(

**Comment by awalterschulze** [comment]
I assume ppc64tel is also a big endian architecture.
So it belongs to this issue
https://github.com/gogo/protobuf/issues/195

I need a build server for big endian architectures, for me to make this fix.  
Without a build server, this will simply break again in future.
But a pull request with a fix from someone else will still be appreciated.
Otherwise I would recommend not using unsafe on big endian.

**Comment by TheTincho** [comment]
Hey, sorry for the delay, I did not receive the notifications..

ppc64el is actually little-endian (ppc64 is the big-endian variant).

In any case, I can happily test any patches you send my way. I can't share the access (these are debian machines), but I can test myself.

**Comment by awalterschulze** [comment]
Hopefully this solves it
https://github.com/gogo/protobuf/issues/333
So once that is completed, I'll ask you to rerun this again.

**Comment by TheTincho** [comment]
Thanks, let me know!

**Comment by awalterschulze** [comment]
Could you rerun with the newest release version 0.5

I have removed a lot of unsafe, so I hope this will fix everything.

**Comment by awalterschulze** [comment]
@TheTincho ^^

**Comment by TheTincho** [comment]
I have just tested it on a Debian porter box, and it seems to build fine!

I will now upload 0.5 to Debian and see if the official builders do not complain.

**Comment by awalterschulze** [comment]
Looking forward to the results. Thank you for your efforts. I appreciate
it.

**Comment by TheTincho** [comment]
Yup. Compiled fine in all arches. Thanks!!

https://buildd.debian.org/status/package.php?p=golang-gogoprotobuf

**Comment by awalterschulze** [comment]
Thank you so much :D
This is a big relief!
