### ISSUE TITLE
Non-pointer fields aren't registered when using goproto_registration = true

### ISSUE THREAD

**Issue by utrack** [gogo/protobuf#332]
Hi,

My protofile uses option `option (gogoproto.goproto_registration) = true;`, and some fields are set with ` [(gogoproto.nullable) = false];` option. When I'm trying to marshal this proto message via google/protobuf jsonpb I get a panic:
```
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for Images []listingpb.ProductImage [GetProperties]
proto: no coders for listingpb.ProductMeta
proto: no encoder for Meta listingpb.ProductMeta [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for ProductSticker []listingpb.WidgetProductSticker [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for Promotions []listingpb.Promotion [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for Images []listingpb.ProductImage [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for Offers []listingpb.HighlightOffer [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
2017/09/07 08:30:56 http: panic serving 10.103.28.2:30970: reflect.Value.Addr of unaddressable value
goroutine 6217 [running]:
net/http.(*conn).serve.func1(0xc42028cc80)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xed9b00, 0xc421688c80)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
reflect.Value.Addr(0xfc1f00, 0xc4213556e0, 0x99, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:239 +0xb3
listing_api/vendor/github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0xc4201c32c0, 0xc421581af8, 0xc421059400, 0xfc1f00, 0xc4213556e0, 0x99, 0x0, 0x0, 0x99, 0x110a560)
	/go/src/listing_api/vendor/github.com/golang/protobuf/jsonpb/jsonpb.go:499 +0xb16
listing_api/vendor/github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0xc4201c32c0, 0xc421581af8, 0xc421059400, 0xf3b200, 0xc421672e80, 0x195, 0x0, 0x0, 0x10bf3eb, 0x1)
...
```

It doesn't appear when using gogo/protobuf jsonpb for marshalling. I suspect that non-nullable fields are registered incorrectly in google/protobuf registry.

**Comment by utrack** [comment]
Or, maybe, they aren't passed by ptr but rather by value to the marshaler? I'll investigate further.

**Comment by awalterschulze** [comment]
Could you include a proto file that causes the error?

**Comment by utrack** [comment]
@awalterschulze Try `go test` on https://github.com/utrack/gogo-proto-332
It seems that map w/ non-nullable type causes panic.
Non-nullables in arrays cause the `no slice oenc` messages, but they marshal just fine.

**Comment by awalterschulze** [comment]
Yes, so fixing github.com/golang/protobuf/jsonpb to handle maps with non pointer fields, is going to be tough.
Thats where the github.com/gogo/protobuf/jsonpb library comes in and should be able to handle your structure.

**Comment by awalterschulze** [comment]
I am closing, but if you want to reopen please just comment again.
