### ISSUE TITLE
customtype does not work for `int`

### ISSUE THREAD

**Issue by ebuchman** [gogo/protobuf#359]
Protobuf doesn't support `int`, so I though it might be clever to use`int32` with `customtype` to generate code with `int`. The code generation works just fine, but the marshalling panics:

```
panic: interface conversion: *int is not proto.Marshaler: missing method Marshal

goroutine 6 [running]:
testing.tRunner.func1(0xc4202280f0)
        /usr/local/opt/go/libexec/src/testing/testing.go:711 +0x2d2
panic(0x14c88a0, 0xc420061b00)
        /usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/tendermint/abci/vendor/github.com/gogo/protobuf/proto.(*Buffer).enc_custom_ref_bytes(0xc42007fd40, 0xc420196d80, 0xc4200fc480, 0x17f2301, 0xc420046440)
``` 

Note it refers to `*int`, though there is no `*int` in the generated code, only `int`!

# Versions

gogo: v0.5
protoc: v3.4.0
golang: 1.9.2

**Comment by awalterschulze** [comment]
Yes the internals of the github.com/gogo/protobuf/proto library does not support type `int`.  The pointer is typically taken to make is possible to edit the value.
Have you tried generating the marshaler and unmarshaler, that might hold you over?

Obviously the more thorough route would be to add `int` as a supported type inside the proto library.  But that would be tricky and diverge our diff from golang/protobuf in an already tricky file even more.

**Comment by awalterschulze** [comment]
What did you decide to do?
