### ISSUE TITLE
panic: protobuf tag not enough fields in Time.wall

### ISSUE THREAD

**Issue by drew-moore** [gogo/protobuf#408]
We're seeing panics on deserializing message types with `(gogoproto.stdtime)`-annotated fields. The stack trace is copied below, and I pushed a repo [here](https://github.com/drew-moore/gogo-stdtime-issue) demonstrating the issue. 

Are we doing something wrong here? 

vendor.json is checked into the repo - let me know what else would be helpful. 

```
panic: protobuf tag not enough fields in Time.wall: 

goroutine 1 [running]:
/path/to/vendor/github.com/golang/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc4202360a0)
        /path/to/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:325 +0x1666
/path/to/vendor/github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc4202360a0, 0xc420232080, 0xc42022e001, 0x0, 0x0, 0x7, 0x7)
        /path/to/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:134 +0xc0b
/path/to/vendor/github.com/golang/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc42022e001, 0x0, 0x1, 0xc42000e0d0, 0x2, 0xc420067818, 0x412d5c, 0xc420204288, 0xc4200678e0, 0x10)
        /path/to/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:1562 +0x12a
/path/to/vendor/github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc420236000, 0xc42000e0d0, 0xc42022e000, 0x2, 0x2, 0xc420067968, 0x412278)
        /path/to/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:171 +0x7b7
/path/to/vendor/github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc420232000, 0x7f2e4bc0f260, 0xc42000e0d0, 0xc42022e000, 0x2, 0x2, 0xc4200e4580, 0xc4200e45a8)
        /path/to/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:63 +0x75
/path/to/vendor/github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc420230008, 0x7f2e4bc0f260, 0xc42000e0d0, 0x0, 0x0)
        /path/to/vendor/github.com/golang/protobuf/proto/decode.go:425 +0x1ee
/path/to/vendor/google.golang.org/grpc/encoding/proto.codec.Unmarshal(0xc42022e000, 0x2, 0x2, 0x8b6680, 0xc42000e0d0, 0x0, 0x0)
        /path/to/vendor/google.golang.org/grpc/encoding/proto/proto.go:93 +0x133
/path/to/vendor/google.golang.org/grpc.recv(0xc4201668c0, 0x7f2e4bc0f170, 0xc27ce8, 0xc42018e0f0, 0x0, 0x0, 0x8b6680, 0xc42000e0d0, 0x400000, 0x0, ...)
        /path/to/vendor/google.golang.org/grpc/rpc_util.go:597 +0x2d1
/path/to/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc42008fee0, 0x8b6680, 0xc42000e0d0, 0x0, 0x0)
        /path/to/vendor/google.golang.org/grpc/stream.go:508 +0x132
/path/to/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc42018c280, 0x8b6680, 0xc42000e0d0, 0x0, 0x0)
        /path/to/vendor/google.golang.org/grpc/stream.go:384 +0x43
/path/to/vendor/google.golang.org/grpc.invoke(0x985000, 0xc42002a0f0, 0x9312e6, 0x1e, 0x8e2120, 0xc4201667e0, 0x8b6680, 0xc42000e0d0, 0xc4200b7900, 0x0, ...)
        /path/to/vendor/google.golang.org/grpc/call.go:83 +0x183
/path/to/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc4200b7900, 0x985000, 0xc42002a0f0, 0x9312e6, 0x1e, 0x8e2120, 0xc4201667e0, 0x8b6680, 0xc42000e0d0, 0x0, ...)
        /path/to/vendor/google.golang.org/grpc/call.go:37 +0x1b3
/path/to/vendor/google.golang.org/grpc.Invoke(0x985000, 0xc42002a0f0, 0x9312e6, 0x1e, 0x8e2120, 0xc4201667e0, 0x8b6680, 0xc42000e0d0, 0xc4200b7900, 0x0, ...)
        /path/to/vendor/google.golang.org/grpc/call.go:60 +0xc1
main.(*thingServiceClient).GetThing(0xc42000e0c8, 0x985000, 0xc42002a0f0, 0xc4201667e0, 0x0, 0x0, 0x0, 0xc4200b7900, 0x0, 0x0)
        /path/to/thing.pb.go:83 +0xd2
main.runClient()
        /path/to/client.go:21 +0x219
main.main()
        /path/to/main.go:6 +0x25

```

**Comment by awalterschulze** [comment]
The problem is that grpc is calling golang protobuf to marshal your
message. But golang protobuf does not understand time.Time
GitHub.com/gogo/grpc-example is a repo created to show you how to make
gogoprotobuf and grpc play nice.
Please let us know if it helps or if you need more help.
Sorry for the inconvenience.

**Comment by drew-moore** [comment]
Ah, got it. Thanks!
