### ISSUE TITLE
Unable to casttype extension with non generated code when purego build tags

### ISSUE THREAD

**Issue by s-hashimoto00** [gogo/protobuf#448]
go version:
```
$ go version
go version go1.10.3 linux/amd64
```

without build tags:
```
$ go test ./test/casttype/...
?       github.com/gogo/protobuf/test/casttype  [no test files]
ok      github.com/gogo/protobuf/test/casttype/combos/both      0.014s
ok      github.com/gogo/protobuf/test/casttype/combos/marshaler 0.005s
ok      github.com/gogo/protobuf/test/casttype/combos/neither   0.004s
ok      github.com/gogo/protobuf/test/casttype/combos/unmarshaler       0.004s
```

with purego build tags:
```
$ go test -tags purego ./test/casttype/...
?       github.com/gogo/protobuf/test/casttype  [no test files]
ok      github.com/gogo/protobuf/test/casttype/combos/both      0.005s
--- FAIL: TestCastawayProto (0.00s)
panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64 [recovered]
        panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64

goroutine 18 [running]:
testing.tRunner.func1(0xc4200be0f0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x67bd80, 0xc420082b40)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gogo/protobuf/proto.pointer.toUint64Ptr(0xc420082b00, 0xc42006ad10, 0x16, 0x5b006524)
        /go/src/github.com/gogo/protobuf/proto/pointer_reflect.go:202 +0x7e
github.com/gogo/protobuf/proto.unmarshalUint64Ptr(0xc4200d0012, 0x499, 0x499, 0xc420082b00, 0xc42006ad10, 0x16, 0x0, 0xc42006ad10, 0x16, 0x49a, ...)
        /go/src/github.com/gogo/protobuf/proto/table_unmarshal.go:851 +0xc3
github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc4200aa2a0, 0x6bac00, 0xc42006ad00, 0x16, 0xc4200d0012, 0x499, 0x499, 0x7f83e2619088, 0x4ab)
        /go/src/github.com/gogo/protobuf/proto/table_unmarshal.go:173 +0xa0f
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0x83e000, 0x6f5d00, 0xc42006ad00, 0xc4200d0000, 0x4ab, 0x4ab, 0x1, 0x7f83e2619088)
        /go/src/github.com/gogo/protobuf/proto/table_unmarshal.go:63 +0x97
github.com/gogo/protobuf/test/casttype/combos/marshaler.(*Castaway).XXX_Unmarshal(0xc42006ad00, 0xc4200d0000, 0x4ab, 0x4ab, 0xc42006ad00, 0xc420044d01)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/marshaler/casttype.pb.go:64 +0x61
github.com/gogo/protobuf/proto.Unmarshal(0xc4200d0000, 0x4ab, 0x4ab, 0x6f5d00, 0xc42006ad00, 0x0, 0x0)
        /go/src/github.com/gogo/protobuf/proto/decode.go:338 +0x1ad
github.com/gogo/protobuf/test/casttype/combos/marshaler.TestCastawayProto(0xc4200be0f0)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/marshaler/casttypepb_test.go:31 +0x30c
testing.tRunner(0xc4200be0f0, 0x6d5470)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/gogo/protobuf/test/casttype/combos/marshaler 0.005s
--- FAIL: TestCastawayProto (0.00s)
panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64 [recovered]
        panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64

goroutine 5 [running]:
testing.tRunner.func1(0xc4200a60f0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x678d80, 0xc420054a00)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gogo/protobuf/proto.pointer.toUint64Ptr(0xc4200549c0, 0xc420066830, 0x16, 0x196)
        /go/src/github.com/gogo/protobuf/proto/pointer_reflect.go:202 +0x7e
github.com/gogo/protobuf/proto.sizeVarint64Ptr(0xc4200549c0, 0xc420066830, 0x16, 0x1, 0x1)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:1143 +0x43
github.com/gogo/protobuf/proto.(*marshalInfo).size(0xc420066a90, 0x6b7980, 0xc420066820, 0x16, 0x7f635a3fe060)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:198 +0x134
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Size(0x839fe0, 0x6f2a40, 0xc420066820, 0x7f635a3fe060)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:129 +0xdd
github.com/gogo/protobuf/test/casttype/combos/neither.(*Castaway).XXX_Size(0xc420066820, 0x6f2a40)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/neither/casttype.pb.go:71 +0x43
github.com/gogo/protobuf/proto.Marshal(0x6f2a40, 0xc420066820, 0xc420099500, 0xc420066820, 0xc420099500, 0x1, 0x2)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:2735 +0x265
github.com/gogo/protobuf/test/casttype/combos/neither.TestCastawayProto(0xc4200a60f0)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/neither/casttypepb_test.go:26 +0x1b1
testing.tRunner(0xc4200a60f0, 0x6d23f8)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/gogo/protobuf/test/casttype/combos/neither   0.004s
--- FAIL: TestCastawayProto (0.00s)
panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64 [recovered]
        panic: interface conversion: interface {} is **casttype.MyUint64Type, not **uint64

goroutine 5 [running]:
testing.tRunner.func1(0xc4200a60f0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x67dea0, 0xc420054a00)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gogo/protobuf/proto.pointer.toUint64Ptr(0xc4200549c0, 0xc420066760, 0x16, 0x196)
        /go/src/github.com/gogo/protobuf/proto/pointer_reflect.go:202 +0x7e
github.com/gogo/protobuf/proto.sizeVarint64Ptr(0xc4200549c0, 0xc420066760, 0x16, 0x1, 0x1)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:1143 +0x43
github.com/gogo/protobuf/proto.(*marshalInfo).size(0xc4200668f0, 0x6bcac0, 0xc420066750, 0x16, 0x7f0f2aa5b060)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:198 +0x134
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Size(0x841000, 0x6f8120, 0xc420066750, 0x7f0f2aa5b060)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:129 +0xdd
github.com/gogo/protobuf/test/casttype/combos/unmarshaler.(*Castaway).XXX_Size(0xc420066750, 0x6f8120)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/unmarshaler/casttype.pb.go:74 +0x43
github.com/gogo/protobuf/proto.Marshal(0x6f8120, 0xc420066750, 0xc420099500, 0xc420066750, 0xc420099500, 0x1, 0x2)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:2735 +0x265
github.com/gogo/protobuf/test/casttype/combos/unmarshaler.TestCastawayProto(0xc4200a60f0)
        /go/src/github.com/gogo/protobuf/test/casttype/combos/unmarshaler/casttypepb_test.go:26 +0x1b1
testing.tRunner(0xc4200a60f0, 0x6d7908)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/gogo/protobuf/test/casttype/combos/unmarshaler       0.004s
```

**Comment by awalterschulze** [comment]
Thank you for reporting :)

Are you also interested in attempting a fix for this one?

**Comment by s-hashimoto00** [comment]
Thank you for response.

I think so trying fix this issue.
But casttype support is performance may be degraded for non generated marshal/unmarshal.

**Comment by s-hashimoto00** [comment]
> So in general I think we are open to degrading performance for non generated code, since the generating option exists and it is the user's choice, what they deem to be important.

OK, I will implement to only affect for non generated purego `casttype` fields.
