### ISSUE TITLE
Unable to nullable extension with non generated code when purego build tags

### ISSUE THREAD

**Issue by s-hashimoto00** [gogo/protobuf#449]
Nullable extention is generated field without a pointer.
But required field is checked by reflect.Value.IsNil().

go version:
```
$ go version
go version go1.10.3 linux/amd64
```

without build tags:
```
$ go test ./test/unmarshalmerge/
ok      github.com/gogo/protobuf/test/unmarshalmerge    0.003s
```

with purego build tags:
```
$ go test -tags purego ./test/unmarshalmerge/
--- FAIL: TestInt64Merge (0.00s)
panic: reflect: call of reflect.Value.IsNil on int64 Value [recovered]
        panic: reflect: call of reflect.Value.IsNil on int64 Value

goroutine 7 [running]:
testing.tRunner.func1(0xc4200a82d0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x66f320, 0xc42000a200)
        /usr/local/go/src/runtime/panic.go:502 +0x229
reflect.Value.IsNil(0x65ddc0, 0xc420094cb0, 0x186, 0x186)
        /usr/local/go/src/reflect/value.go:1018 +0x11d
github.com/gogo/protobuf/proto.pointer.isNil(0x65ddc0, 0xc420094cb0, 0x186, 0x65ddc0)
        /go/src/github.com/gogo/protobuf/proto/pointer_reflect.go:101 +0x3f
github.com/gogo/protobuf/proto.(*marshalInfo).marshal(0xc420066dd0, 0xc42007c050, 0x0, 0x4b, 0x6af480, 0xc420094cb0, 0x16, 0x0, 0xc42002fd80, 0x4b, ...)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:284 +0x663
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Marshal(0x82efc0, 0xc42007c050, 0x0, 0x4b, 0x6eb3e0, 0xc420094cb0, 0xc420048e00, 0x43e797, 0x50, 0x65e6c0, ...)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:145 +0x17b
github.com/gogo/protobuf/test/unmarshalmerge.(*IntMerge).XXX_Marshal(0xc420094cb0, 0xc42007c050, 0x0, 0x4b, 0x0, 0x4b, 0xc420064d20, 0xc400000002, 0x6f4c8dcd00000001, 0xc42002fea8)
        /go/src/github.com/gogo/protobuf/test/unmarshalmerge/unmarshalmerge.pb.go:184 +0x77
github.com/gogo/protobuf/proto.Marshal(0x6eb3e0, 0xc420094cb0, 0xc4200b6001, 0xc420094cb0, 0xc4200b6000, 0x1, 0x80e16a)
        /go/src/github.com/gogo/protobuf/proto/table_marshal.go:2737 +0x2bf
github.com/gogo/protobuf/test/unmarshalmerge.TestInt64Merge(0xc4200a82d0)
        /go/src/github.com/gogo/protobuf/test/unmarshalmerge/unmarshalmerge_test.go:89 +0x1b4
testing.tRunner(0xc4200a82d0, 0x6cc2e8)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/gogo/protobuf/test/unmarshalmerge    0.004s
```

**Comment by awalterschulze** [comment]
Thank you for reporting.

Are you interested in attempting a fix?

**Comment by s-hashimoto00** [comment]
Thank you for response.

I think so trying fix this issue.

**Comment by awalterschulze** [comment]
Thank you that is super helpful, we really appreciate all the help we can get :)
