### ISSUE TITLE
OneOf marshal/unmarshal panics when casttype int is used

### ISSUE THREAD

**Issue by ericrenard** [gogo/protobuf#573]
Unmarshal of message with oneof values containing messages with properties using casttype int panics.

Repro steps :

Proto:
message Value {
    int64 Value = 1 [(gogoproto.casttype) = "int"];
}

message Object {
    oneof Object {
        Value Value = 1;
    }
}

Go code:
func TestReproCastTypeBug(t *testing.T) {
	s := &Object{
		Object: &Object_Value{Value: &Value{Value:1}},
	}

	b, err := proto.Marshal(s)
	if err != nil {
		panic(err)
	}
	m := &SectionChannel{}
	err = proto.Unmarshal(b, m)
	if err != nil {
		panic(err)
	}
}

goroutine 7 [running]:
testing.tRunner.func1(0xc0001d4100)
	/usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:830 +0x388
panic(0x18487c0, 0xc000146cc0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:522 +0x1b5
github.com/molotovtv/go-sections/vendor/github.com/gogo/protobuf/proto.typeMarshaler(0x1a91840, 0x1847880, 0xc0000a2ae0, 0x6, 0x6, 0x1, 0x6, 0xc0000a2ae0)
	/Users/erenard/go/src/github.com/molotovtv/go-sections/vendor/github.com/gogo/protobuf/proto/table_marshal.go:1014 +0x2ae7

Same bug but for unmarshal is present in table_unmarshal.go l830.

A case reflect.Int is missing to handle this.

**Comment by jmarais** [comment]
Thanks. 

CastType assumes that the type is castable to the original protobuf field type. In Golang an ```int``` can either be a int32/int64 depending on the platform so we would have to choose which protobuf type it is when marshaling.
