### ISSUE TITLE
Unmarshal panic: index out of range

### ISSUE THREAD

**Issue by howardjohn** [gogo/protobuf#579]
Reproducer:

```go
import (
	"github.com/gogo/protobuf/proto"
	"istio.io/api/networking/v1alpha3"
	"testing"
)

func Test(t *testing.T) {
	i := "2\x12\x12\x10\x12\x00\x12\x00\x12\x002\xf1\xff\xff\xff\xff\xff\xff\xff\u007f"
	bs := []byte(i)
	p := &v1alpha3.ServiceEntry{}
	proto.Unmarshal(bs, p)
}
```

results in

```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 39 [running]:
testing.tRunner.func1(0xc000246100)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1161d60, 0x1edf000)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/vendor/istio.io/api/networking/v1alpha3.(*ServiceEntry_Endpoint).Unmarshal(0xc00020fdc0, 0xc00020a562, 0x12, 0x1e, 0x1, 0xc0001fa040)
	/home/howardjohn/go/src/istio.io/istio/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go:1463 +0x20f2
istio.io/istio/vendor/istio.io/api/networking/v1alpha3.(*ServiceEntry).Unmarshal(0xc000204180, 0xc00020a560, 0x14, 0x20, 0xc00020a501, 0x7f2ac5914090)
	/home/howardjohn/go/src/istio.io/istio/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go:1265 +0x107b
istio.io/istio/vendor/istio.io/api/networking/v1alpha3.(*ServiceEntry).XXX_Unmarshal(0xc000204180, 0xc00020a560, 0x14, 0x20, 0xc000204180, 0xc00006c701)
	/home/howardjohn/go/src/istio.io/istio/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go:503 +0x49
istio.io/istio/vendor/github.com/gogo/protobuf/proto.Unmarshal(0xc00020a560, 0x14, 0x20, 0x14857a0, 0xc000204180, 0x20, 0x47c656)
	/home/howardjohn/go/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/decode.go:337 +0x1bd
istio.io/istio/tests/fuzz.Test(0xc000246100)
	/home/howardjohn/go/src/istio.io/istio/tests/fuzz/scratch_test.go:13 +0xa9
testing.tRunner(0xc000246100, 0x13497f8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
```

From some debugging looks like this `skippy` variable gets too high and overflows int: https://github.com/istio/istio/blob/cc0f7ada51435945559104eda0871aefad956541/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go#L1517. So this check is not true: https://github.com/istio/istio/blob/cc0f7ada51435945559104eda0871aefad956541/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go#L1524 so iNdEx becomes a huge number: https://github.com/istio/istio/blob/cc0f7ada51435945559104eda0871aefad956541/vendor/istio.io/api/networking/v1alpha3/service_entry.pb.go#L1527

This happens on other protos as well if you need more examples.

**Comment by jmarais** [comment]
Hi. Thanks for the issue.

I tried to recreate this with your message definitions and could not succeed (on current master).

Here is the proto definition (taken from the istio.io networking protos):
https://github.com/jmarais/protobuf/blob/issue579/test/issue579/issue579.proto#L33
Here is your supplied test:
https://github.com/jmarais/protobuf/blob/issue579/test/issue579/issue_test.go#L36

Here is my test output:

```bash
$ go version
go version go1.12.4 linux/amd64
$ protoc --version
libprotoc 3.7.1

$ go test -v -run=.
=== RUN   TestSkippyIOOR
--- PASS: TestSkippyIOOR (0.00s)
PASS
ok      github.com/gogo/protobuf/test/issue579  0.002s
```

What versions are you running?

**Comment by howardjohn** [comment]
I thought we were using a recent version but turns out we are on gogo v1.0 so that is probably the issue
