### ISSUE TITLE
Nil Pointer in MarshalTo/MarshalToSizedBuffer

### ISSUE THREAD

**Issue by un000** [gogo/protobuf#651]
Got a grpc handler:
```
func (h *hello) Echo(ctx context.Context, req *pb.Payload) (*pb.Payload, error) {
	var res *pb.Payload    // <<<< typed nil
	return res, nil
}
```

With default grpc-library there is no panic, *protobuf 1.3.2* returns to a client an error:
```
	ErrNil = errors.New("proto: Marshal called with nil")
```

But with gogofaster grpc server crashes with a panic:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14964a6]

goroutine 51 [running]:
github.com/myorg/hello/example/pb.(*Payload).MarshalToSizedBuffer(0x0, 0x1ab1d58, 0x0, 0x0, 0x100bd73, 0x15879e0, 0x15fca60)
        /Users/un0/go/src/github.com/myorg/hello/example/pb/hello.pb.go:192 +0x26
github.com/myorg/hello/example/pb.(*Payload).Marshal(0x0, 0x15fca60, 0x0, 0x4a000a0, 0x0, 0x15fca01)
        /Users/un0/go/src/github.com/myorg/hello/example/pb/hello.pb.go:175 +0xc3
google.golang.org/grpc/encoding/proto.codec.Marshal(0x15fca60, 0x0, 0xc000211070, 0x0, 0x100a9bb, 0xc000012000, 0x158b820)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/encoding/proto/proto.go:70 +0x194
google.golang.org/grpc.encode(0x4a00028, 0x1ab1d58, 0x15fca60, 0x0, 0x1ab1d58, 0x100a9bb, 0xc000012000, 0x1587f60, 0x1573ca0)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/rpc_util.go:543 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc0000eac60, 0x16f6840, 0xc000001e00, 0xc0001ba100, 0x15fca60, 0x0, 0x0, 0x0, 0xc0001a807c, 0x0, ...)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:833 +0x89
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000eac60, 0x16f6840, 0xc000001e00, 0xc0001ba100, 0xc00008fb90, 0x1a85230, 0x0, 0x0, 0x0)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1030 +0x551
google.golang.org/grpc.(*Server).handleStream(0xc0000eac60, 0x16f6840, 0xc000001e00, 0xc0001ba100, 0x0)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002a5c0, 0xc0000eac60, 0x16f6840, 0xc000001e00, 0xc0001ba100)
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/un0/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1

```

Generated code:
```
func (m *Payload) MarshalTo(dAtA []byte) (int, error) {
        // <<< here should be `if m == nil`  check >>>
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {                   // <<<< panics
```

There should be the check for a backward compatibility.

**Comment by un000** [comment]
@awalterschulze @jmarais what do you think about that? Should I commit this change?

**Comment by alexshtin** [comment]
I am having the same problem here. Basically every time when `error` is `nil`, payload must be not `nil` which is really annoying. Added checks to handlers for now, but this is very error prone.

Can we fix it? I don't want to switch to standard gRCP library due to number of reasons.

**Comment by kevindiu** [comment]
Is there any update on this issue?
This panic still occur in my environment and causing the application down...

**Comment by jansoneo** [comment]
gogofaster  is non-thread-safe
