### ISSUE TITLE
Multiple imports using gogo/protobuf causes duplicate extension registered

### ISSUE THREAD

**Issue by triplewy** [gogo/protobuf#672]
In my go project, I am importing jaeger/jaeger-tracing and istio/client-go which each use gogo/protobuf. When I try to run my project, I get this error:
```
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterExtension(0x30a32e0)
	/Users/alexyu/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/extensions.go:595 +0x2cb
github.com/gogo/googleapis/google/api.init.0()
	/Users/alexyu/go/pkg/mod/github.com/gogo/googleapis@v1.0.1-0.20180501115203-b23578765ee5/google/api/annotations.pb.go:26 +0x2d
exit status 2
```

Is there anyway to import multiple packages that use gogo/protobuf in a single project?

**Comment by hazcod** [comment]
Seen this in https://github.com/temporalio/go-sdk/issues/236

**Comment by hazcod** [comment]
Did you find a way to fix this @triplewy ?

**Comment by triplewy** [comment]
I was able to fix this issue using Go modules instead of the old packaging solution whose name escapes me right now

**Comment by hazcod** [comment]
Hm, I have the issue with vendor/ and go modules.

**Comment by shuxnhs** [comment]
Did you find a way to fix this @triplewy @hazcod ??

**Comment by hazcod** [comment]
In the end the project used a workaround by shuffling their files round I think..

**Comment by shuxnhs** [comment]
> In the end the project used a workaround by shuffling their files round I think..

sorry, what does `a workaround by shuffling their files round` mean?
