### ISSUE TITLE
oom

### ISSUE THREAD

**Issue by niupanyu** [gogo/protobuf#754]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x7e6913, 0x16)
        /usr/lib/golang/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc96c000000, 0x35c000000, 0xb389b8)
        /usr/lib/golang/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xb20260, 0x35c000000, 0x80, 0xc000a33e30)
        /usr/lib/golang/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xb20260, 0x1ac19a, 0x0)
        /usr/lib/golang/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xb20260, 0x1ac19a, 0xb389c8, 0xc000a33ed8)
        /usr/lib/golang/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xb20260, 0x1ac19a, 0xc001550101, 0x1)
        /usr/lib/golang/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/golang/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xb20260, 0x1ac19a, 0x300000101, 0xc000000300)
        /usr/lib/golang/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x358334000, 0xc000510100, 0xc000534f01)
        /usr/lib/golang/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/golang/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/lib/golang/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/golang/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/golang/src/runtime/asm_amd64.s:311 fp=0xc00ca1e640 sp=0xc00ca1e638 pc=0x453d90
runtime.mallocgc(0x358334000, 0x0, 0xc00ca1e700, 0x4c6478)
        /usr/lib/golang/src/runtime/malloc.go:913 +0x896 fp=0xc00ca1e6e0 sp=0xc00ca1e640 pc=0x40b916
runtime.growslice(0x770c00, 0xc6a7dd8000, 0x2acf5bfe3, 0x2acf5c000, 0x2acf5c013, 0xc00ca1e7a8, 0x5b32b1, 0xc0010469c0)
        /usr/lib/golang/src/runtime/slice.go:197 +0x219 fp=0xc00ca1e748 sp=0xc00ca1e6e0 pc=0x43f9c9
go/printer.(*printer).writeString(0xc00ca217e8, 0x0, 0x0, 0xd77a74b, 0x206f9, 0x2, 0xc0010469c0, 0x30, 0x20601)
        /usr/lib/golang/src/go/printer/printer.go:310 +0x356 fp=0xc00ca1e7b8 sp=0xc00ca1e748 pc=0x5b2d06
go/printer.(*printer).writeComment(0xc00ca217e8, 0xc00639ba60)
        /usr/lib/golang/src/go/printer/printer.go:652 +0x47a fp=0xc00ca1e890 sp=0xc00ca1e7b8 pc=0x5b3f6a
go/printer.(*printer).intersperseComments(0xc00ca217e8, 0x0, 0x0, 0x40000c51, 0x7ac9f, 0x1a72, 0x38, 0x1a72)
        /usr/lib/golang/src/go/printer/printer.go:748 +0x11b fp=0xc00ca1e988 sp=0xc00ca1e890 pc=0x5b42bb
go/printer.(*printer).flush(0xc00ca217e8, 0x0, 0x0, 0x40000c51, 0x7ac9f, 0x1a72, 0x38, 0x40000c51)
        /usr/lib/golang/src/go/printer/printer.go:1022 +0xb7 fp=0xc00ca1ea00 sp=0xc00ca1e988 pc=0x5b50a7
go/printer.(*printer).print(0xc00ca217e8, 0xc00ca1eb30, 0x2, 0x2)
        /usr/lib/golang/src/go/printer/printer.go:982 +0x274 fp=0xc00ca1eb00 sp=0xc00ca1ea00 pc=0x5b49c4
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7c37d0, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1052 +0x1c1 fp=0xc00ca1eb80 sp=0xc00ca1eb00 pc=0x5ac4b1
go/printer.(*printer).stmt(0xc00ca217e8, 0x882340, 0xc11e7c1700, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1260 +0x22f3 fp=0xc00ca1f158 sp=0xc00ca1eb80 pc=0x5aefa3
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e791c00, 0x6, 0x8, 0x1, 0xb03201)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca1f1e0 sp=0xc00ca1f158 pc=0x5ac140
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7c3800, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1050 +0xed fp=0xc00ca1f260 sp=0xc00ca1f1e0 pc=0x5ac3dd
go/printer.(*printer).stmt(0xc00ca217e8, 0x882180, 0xc11e7c1740, 0x0)
        /usr/lib/golang/src/go/printer/nodes.go:1326 +0x60f fp=0xc00ca1f838 sp=0xc00ca1f260 pc=0x5ad2bf
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e7c1800, 0x3, 0x4, 0x1, 0xb03201)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca1f8c0 sp=0xc00ca1f838 pc=0x5ac140
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7c3830, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1050 +0xed fp=0xc00ca1f940 sp=0xc00ca1f8c0 pc=0x5ac3dd
go/printer.(*printer).stmt(0xc00ca217e8, 0x882340, 0xc11e7cc380, 0x100)
        /usr/lib/golang/src/go/printer/nodes.go:1260 +0x22f3 fp=0xc00ca1ff18 sp=0xc00ca1f940 pc=0x5aefa3
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e7c84f0, 0x1, 0x1, 0x1, 0x0)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca1ffa0 sp=0xc00ca1ff18 pc=0x5ac140
go/printer.(*printer).stmt(0xc00ca217e8, 0x881f40, 0xc11e7cc3c0, 0x7fb2c0cc0100)
        /usr/lib/golang/src/go/printer/nodes.go:1284 +0x20e8 fp=0xc00ca20578 sp=0xc00ca1ffa0 pc=0x5aed98
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e791e00, 0x6, 0x8, 0x0, 0xb03201)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca20600 sp=0xc00ca20578 pc=0x5ac140
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7ca9c0, 0x0)
        /usr/lib/golang/src/go/printer/nodes.go:1050 +0xed fp=0xc00ca20680 sp=0xc00ca20600 pc=0x5ac3dd
go/printer.(*printer).stmt(0xc00ca217e8, 0x882780, 0xc11e7ca9f0, 0x101)
        /usr/lib/golang/src/go/printer/nodes.go:1289 +0xdce fp=0xc00ca20c58 sp=0xc00ca20680 pc=0x5ada7e
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e791880, 0x8, 0x8, 0x1, 0xb03201)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca20ce0 sp=0xc00ca20c58 pc=0x5ac140
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7caa20, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1050 +0xed fp=0xc00ca20d60 sp=0xc00ca20ce0 pc=0x5ac3dd
go/printer.(*printer).stmt(0xc00ca217e8, 0x882180, 0xc11e7cc680, 0x0)
        /usr/lib/golang/src/go/printer/nodes.go:1326 +0x60f fp=0xc00ca21338 sp=0xc00ca20d60 pc=0x5ad2bf
go/printer.(*printer).stmtList(0xc00ca217e8, 0xc11e791f00, 0x5, 0x8, 0x1, 0xc00ca21401)
        /usr/lib/golang/src/go/printer/nodes.go:1027 +0x170 fp=0xc00ca213c0 sp=0xc00ca21338 pc=0x5ac140
go/printer.(*printer).block(0xc00ca217e8, 0xc11e7cab10, 0x1)
        /usr/lib/golang/src/go/printer/nodes.go:1050 +0xed fp=0xc00ca21440 sp=0xc00ca213c0 pc=0x5ac3dd
go/printer.(*printer).funcBody(0xc00ca217e8, 0x3e, 0xb, 0xc11e7cab10)
        /usr/lib/golang/src/go/printer/nodes.go:1687 +0x4b4 fp=0xc00ca21558 sp=0xc00ca21440 pc=0x5b13d4
go/printer.(*printer).funcDecl(0xc00ca217e8, 0xc11e7cab40)
        /usr/lib/golang/src/go/printer/nodes.go:1711 +0x193 fp=0xc00ca215c8 sp=0xc00ca21558 pc=0x5b16d3
go/printer.(*printer).decl(0xc00ca217e8, 0x8821c0, 0xc11e7cab40)
        /usr/lib/golang/src/go/printer/nodes.go:1721 +0x160 fp=0xc00ca21618 sp=0xc00ca215c8 pc=0x5b18c0
go/printer.(*printer).declList(0xc00ca217e8, 0xc03d1e4000, 0x6a99, 0x7800)
        /usr/lib/golang/src/go/printer/nodes.go:1764 +0x12c fp=0xc00ca21690 sp=0xc00ca21618 pc=0x5b1a8c
go/printer.(*printer).file(0xc00ca217e8, 0xc11e8e4600)
        /usr/lib/golang/src/go/printer/nodes.go:1772 +0x13a fp=0xc00ca21700 sp=0xc00ca21690 pc=0x5b1cba
go/printer.(*printer).printNode(0xc0079717e8, 0x787140, 0xc11e8e4600, 0xc11e8c9750, 0x0)
        /usr/lib/golang/src/go/printer/printer.go:1152 +0x59c fp=0xc00ca217a8 sp=0xc00ca21700 pc=0x5b5a2c
go/printer.(*Config).fprint(0xc00ca21a68, 0x87f160, 0xc00010e000, 0xc005143140, 0x787140, 0xc11e8e4600, 0xc11e8e9950, 0xd, 0x1acf)
        /usr/lib/golang/src/go/printer/printer.go:1293 +0x170 fp=0xc00ca21950 sp=0xc00ca217a8 pc=0x5b64b0
go/printer.(*Config).Fprint(0xc007971a68, 0x87f160, 0xc00010e000, 0xc005143140, 0x787140, 0xc11e8e4600, 0xc11e8e4600, 0x0)
        /usr/lib/golang/src/go/printer/printer.go:1351 +0x72 fp=0xc00ca219a8 sp=0xc00ca21950 pc=0x5b6752
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).generate(0xc00010e000, 0xc004a79b80)
        /data/home/user00/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go:1277 +0xb97 fp=0xc00ca21d58 sp=0xc00ca219a8 pc=0x60c617
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).GenerateAllFiles(0xc00010e000)
        /data/home/user00/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go:1160 +0x27e fp=0xc00ca21ea8 sp=0xc00ca21d58 pc=0x60b47e
github.com/gogo/protobuf/vanity/command.Generate(0xc00009e420, 0x5)
        /data/home/user00/github.com/gogo/protobuf/vanity/command/command.go:131 +0x17f fp=0xc00ca21f30 sp=0xc00ca21ea8 pc=0x73c99f
main.main()
        /data/home/user00/github.com/gogo/protobuf/protoc-gen-gogofaster/main.go:50 +0x1e4 fp=0xc00ca21f98 sp=0xc00ca21f30 pc=0x73d194
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:201 +0x207 fp=0xc00ca21fe0 sp=0xc00ca21f98 pc=0x42bb07
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00ca21fe8 sp=0xc00ca21fe0 pc=0x455cf1
--gogofaster_out: protoc-gen-gogofaster: Plugin failed with status code 2.

**Comment by hitzhangjie** [comment]
Yes, it's really easy to fix it.

Just change the `generator.(*Generator).In()` and `generator.(*Generator).Out()` to empty. Or you can fix the relevant plugin as I told below.

---

The problem behind this is, gogofast customize some plugins, including unmarshal, defaultcheck, .... Well, unmarshal plugin generating functions but their indent level isn't right. If your protofile contains many messages, the indenting problems will be amplified and consumes too much memory.

ps: In my maintained project, there's a huge protofile, which has 2k+ messages and each message contains 5 or more primitive fields, and my machine is 64GB RAM, get OOM killed.
