### ISSUE TITLE
Bug: sizer's Size method breaks with onlyone & oneof

### ISSUE THREAD

**Issue by benburkert** [gogo/protobuf#84]
With a proto file that uses both sizer & onlyone/oneof:

```protobufs
syntax = "proto3";

package main;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.sizer_all) = true;

message FooBar {
  message Foo {
    string baz = 1;
  }

  message Bar {
    string baz = 1;
  }

  option (gogoproto.onlyone) = true;

  oneof foobar {
    Foo foo = 1;
    Bar bar = 2;
  }
}
```

The following program will crash:

```go
package main

//go:generate protoc --proto_path=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:. --gogo_out=. foobar.proto

func main() {
	fb := &FooBar{Foo: &FooBar_Foo{}}
	fb.Marshal()
}
```

```
$ go build *.go && ./foobar
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x3883]

goroutine 1 [running]:
main.(*FooBar_Bar).Size(0x0, 0x1)
	/Users/benburkert/src/github.com/benburkert/prototest/foobar.pb.go:336 +0x23
main.(*FooBar).Size(0x208259780, 0x2)
	/Users/benburkert/src/github.com/benburkert/prototest/foobar.pb.go:318 +0x82
main.(*FooBar).Marshal(0x208259780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/benburkert/src/github.com/benburkert/prototest/foobar.pb.go:357 +0x55
main.main()
	/Users/benburkert/src/github.com/benburkert/prototest/foobar.go:7 +0x91

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

I think the generated `(*FooBar).Size()` method should check for nil members before calling `Size()`:

```go
func (m *FooBar) Size() (n int) {
	var l int
	_ = l
	l = m.Foo.Size()
	n += 1 + l + sovFoobar(uint64(l))
	l = m.Bar.Size()                                   // m.Bar is nil, boom
	n += 1 + l + sovFoobar(uint64(l))
	return n
} 
```

**Comment by awalterschulze** [comment]
I get the following Size method

```
func (m *FooBar) Size() (n int) {
	var l int
	_ = l
	if m.Foo != nil {
		l = m.Foo.Size()
		n += 1 + l + sovIssue84(uint64(l))
	}
	if m.Bar != nil {
		l = m.Bar.Size()
		n += 1 + l + sovIssue84(uint64(l))
	}
	return n
}
```

**Comment by awalterschulze** [comment]
Maybe try updating your gogoprotobuf?

**Comment by benburkert** [comment]
> Maybe try updating your gogoprotobuf?

yep, looks like that was my problem, sorry!

**Comment by awalterschulze** [comment]
No Problem :)
May I ask where you are using gogoprotobuf?
